export const AG_GRID_LOCALE_AR = {
  // فلتر الأرقام والنصوص
  filterOoo: 'فلتر...',
  equals: 'يساوي',
  notEqual: 'لا يساوي',
  blank: 'فارغ',
  notBlank: 'غير فارغ',
  empty: 'اختر واحدة',

  // فلتر الأرقام
  lessThan: 'أقل من',
  greaterThan: 'أكبر من',
  lessThanOrEqual: 'أقل من أو يساوي',
  greaterThanOrEqual: 'أكبر من أو يساوي',
  inRange: 'بين',
  inRangeStart: 'من',
  inRangeEnd: 'إلى',

  // فلتر النصوص
  contains: 'يحتوي على',
  notContains: 'لا يحتوي على',
  startsWith: 'يبدأ بـ',
  endsWith: 'ينتهي بـ',

  // فلتر التاريخ
  dateFormatOoo: 'سنة-شهر-يوم',
  before: 'قبل',
  after: 'بعد',

  // شروط الفلتر
  andCondition: 'و',
  orCondition: 'أو',

  // أزرار الفلتر
  applyFilter: 'تطبيق',
  resetFilter: 'إعادة تعيين',
  clearFilter: 'مسح',
  cancelFilter: 'إلغاء',

  // عناوين الفلتر
  textFilter: 'فلتر النص',
  numberFilter: 'فلتر الأرقام',
  dateFilter: 'فلتر التاريخ',
  setFilter: 'تعيين فلتر',

  // فلتر العمود المجمع
  groupFilterSelect: 'اختر الحقل:',

  // فلتر متقدم
  advancedFilterContains: 'يحتوي',
  advancedFilterNotContains: 'لا يحتوي',
  advancedFilterTextEquals: 'يساوي',
  advancedFilterTextNotEqual: 'لا يساوي',
  advancedFilterStartsWith: 'يبدأ بـ',
  advancedFilterEndsWith: 'ينتهي بـ',
  advancedFilterBlank: 'فارغ',
  advancedFilterNotBlank: 'غير فارغ',
  advancedFilterEquals: '=',
  advancedFilterNotEqual: '!=',
  advancedFilterGreaterThan: '>',
  advancedFilterGreaterThanOrEqual: '>=',
  advancedFilterLessThan: '<',
  advancedFilterLessThanOrEqual: '<=',
  advancedFilterTrue: 'صحيح',
  advancedFilterFalse: 'غير صحيح',
  advancedFilterAnd: 'و',
  advancedFilterOr: 'أو',
  advancedFilterApply: 'تطبيق',
  advancedFilterBuilder: 'مُنشئ',
  advancedFilterValidationMissingColumn: 'العمود مفقود',
  advancedFilterValidationMissingOption: 'الخيار مفقود',
  advancedFilterValidationMissingValue: 'القيمة مفقودة',
  advancedFilterValidationInvalidColumn: 'العمود غير موجود',
  advancedFilterValidationInvalidOption: 'الخيار غير موجود',
  advancedFilterValidationMissingQuote: 'القيمة بدون اقتباس نهائي',
  advancedFilterValidationNotANumber: 'القيمة ليست رقمًا',
  advancedFilterValidationInvalidDate: 'القيمة ليست تاريخًا صالحًا',
  advancedFilterValidationMissingCondition: 'الشرط مفقود',
  advancedFilterValidationJoinOperatorMismatch: 'عمليات الانضمام ضمن الشرط يجب أن تكون متطابقة',
  advancedFilterValidationInvalidJoinOperator: 'عامل الانضمام غير موجود',
  advancedFilterValidationMissingEndBracket: 'قوس النهاية مفقود',
  advancedFilterValidationExtraEndBracket: 'قوس النهاية زائد',
  advancedFilterValidationMessage: 'التعبير به خطأ. ${variable} - ${variable}.',
  advancedFilterValidationMessageAtEnd: 'التعبير به خطأ. ${variable} في نهاية التعبير.',
  advancedFilterBuilderTitle: 'فلتر متقدم',
  advancedFilterBuilderApply: 'تطبيق',
  advancedFilterBuilderCancel: 'إلغاء',
  advancedFilterBuilderAddButtonTooltip: 'إضافة فلتر أو مجموعة',
  advancedFilterBuilderRemoveButtonTooltip: 'إزالة',
  advancedFilterBuilderMoveUpButtonTooltip: 'نقل لأعلى',
  advancedFilterBuilderMoveDownButtonTooltip: 'نقل لأسفل',
  advancedFilterBuilderAddJoin: 'إضافة مجموعة',
  advancedFilterBuilderAddCondition: 'إضافة فلتر',
  advancedFilterBuilderSelectColumn: 'حدد عمودًا',
  advancedFilterBuilderSelectOption: 'حدد خيارًا',
  advancedFilterBuilderEnterValue: 'أدخل قيمة...',

  // الشريط الجانبي
  columns: 'الأعمدة',
  filters: 'الفلاتر',

  // لوحة أدوات الأعمدة
  pivotMode: 'وضع التحويل المحوري',
  groups: 'مجموعات الصفوف',
  rowGroupColumnsEmptyMessage: 'اسحب هنا لتعيين مجموعات الصفوف',
  values: 'القيم',
  valueColumnsEmptyMessage: 'اسحب هنا للتجميع',
  pivots: 'عناوين الأعمدة',
  pivotColumnsEmptyMessage: 'اسحب هنا لتعيين عناوين الأعمدة',

  // عنوان عمود المجموعة الافتراضي
  group: 'مجموعة',

  // السحب الصفوف
  rowDragRow: 'صف',
  rowDragRows: 'صفوف',

  // آخرى
  loadingOoo: 'جار التحميل...',
  loadingError: 'خطأ',
  noRowsToShow: 'لا توجد صفوف لعرضها',
  enabled: 'ممكّن',

  // القائمة
  pinColumn: 'تثبيت العمود',
  pinLeft: 'تثبيت على اليسار',
  pinRight: 'تثبيت على اليمين',
  noPin: 'لا تثبيت',
  valueAggregation: 'تجميع القيمة',
  noAggregation: 'لا شيء',
  autosizeThiscolumn: 'تحديد حجم هذا العمود تلقائيًا',
  autosizeAllColumns: 'تحديد حجم كافة الأعمدة تلقائيًا',
  groupBy: 'تجميع بواسطة',
  ungroupBy: 'إلغاء التجميع بواسطة',
  ungroupAll: 'إلغاء تجميع الكل',
  addToValues: 'إضافة ${variable} إلى القيم',
  removeFromValues: 'إزالة ${variable} من القيم',
  addToLabels: 'إضافة ${variable} إلى التسميات',
  removeFromLabels: 'إزالة ${variable} من التسميات',
  resetColumns: 'إعادة تعيين الأعمدة',
  expandAll: 'توسيع كافة مجموعات الصفوف',
  collapseAll: 'طي كافة مجموعات الصفوف',
  copy: 'نسخ',
  ctrlC: 'Ctrl+C',
  ctrlX: 'Ctrl+X',
  copyWithHeaders: 'نسخ مع الرؤوس',
  copyWithGroupHeaders: 'نسخ مع رؤوس المجموعة',
  cut: 'قص',
  paste: 'لصق',
  ctrlV: 'Ctrl+V',
  export: 'تصدير',
  csvExport: 'تصدير كملف CSV',
  excelExport: 'تصدير كملف Excel',
  columnFilter: 'فلتر العمود',
  columnChooser: 'اختيار الأعمدة',
  sortAscending: 'ترتيب تصاعدي',
  sortDescending: 'ترتيب تنازلي',
  sortUnSort: 'إلغاء الترتيب',

  // القائمة الفرعية للشركات وشريط الحالة
  sum: 'مجموع',
  first: 'الأول',
  last: 'الأخير',
  min: 'الأدنى',
  max: 'الأعلى',
  none: 'لا شيء',
  count: 'العدد',
  avg: 'المتوسط',
  filteredRows: 'مُصفّى',
  selectedRows: 'محدد',
  totalRows: 'إجمالي الصفوف',
  totalAndFilteredRows: 'الصفوف',
  more: 'المزيد',
  to: 'إلى',
  of: 'من',
  page: 'صفحة',
  pageLastRowUnknown: '?',
  nextPage: 'الصفحة التالية',
  lastPage: 'الصفحة الأخيرة',
  firstPage: 'الصفحة الأولى',
  previousPage: 'الصفحة السابقة',
  pageSizeSelectorLabel: 'حجم الصفحة:',
  footerTotal: 'الإجمالي',

  // التحويل المحوري
  pivotColumnGroupTotals: 'المجموع',

  // القائمة الرئيسية (الرسوم البيانية)
  pivotChartAndPivotMode: 'الرسم البياني المحوري ووضع التحويل المحوري',
  pivotChart: 'الرسم البياني المحوري',
  chartRange: 'نطاق الرسم البياني',

  columnChart: 'عمودي',
  groupedColumn: 'مُجمّع',
  stackedColumn: 'مُكدّس',
  normalizedColumn: 'مُكدّس 100%',

  barChart: 'شريطي',
  groupedBar: 'مُجمّع',
  stackedBar: 'مُكدّس',
  normalizedBar: 'مُكدّس 100%',

  pieChart: 'دائري',
  pie: 'دائري',
  donut: 'دونات',

  line: 'خط',

  xyChart: 'X Y (تشتت)',
  scatter: 'تشتت',
  bubble: 'فقاعة',

  areaChart: 'منطقة',
  area: 'منطقة',
  stackedArea: 'مُكدّس',
  normalizedArea: 'مُكدّس 100%',

  histogramChart: 'هيستوغرام',
  histogramFrequency: "تردد",

  polarChart: 'قطبي',
  radarLine: 'خط رادار',
  radarArea: 'منطقة رادار',
  nightingale: 'نايتنغال',
  radialColumn: 'عمود شعاعي',
  radialBar: 'شريط شعاعي',

  statisticalChart: 'إحصائي',
  boxPlot: 'مخطط الصندوق',
  rangeBar: 'شريط النطاق',
  rangeArea: 'منطقة النطاق',

  hierarchicalChart: 'تسلسلي',
  treemap: 'خريطة الشجرة',
  sunburst: 'تفتيت الشمس',

  specializedChart: 'متخصص',
  waterfall: 'شلال',
  heatmap: 'خريطة حرارية',

  combinationChart: 'مزيج',
  columnLineCombo: 'عمود وخط',
  AreaColumnCombo: 'منطقة وعمود',

  // الرسوم البيانية
  pivotChartTitle: 'الرسم البياني المحوري',
  rangeChartTitle: 'مخطط النطاق',
  settings: 'الرسم البياني',
  data: 'البيانات',
  format: 'التنسيق',
  categories: 'الفئات',
  defaultCategory: '(بلا)',
  series: 'السلاسل',
  switchCategorySeries: 'تبديل الفئة / السلسلة',
  categoryValues: 'قيم الفئة',
  seriesLabels: 'تسميات السلسل',
  aggregate: 'التجميع',
  xyValues: 'قيم XY',
  paired: 'وضع مزدوج',
  axis: 'المحور',
  xAxis: 'المحور الأفقي',
  yAxis: 'المحور العمودي',
  polarAxis: 'المحور القطبي',
  radiusAxis: 'المحور النصفي',
  navigator: 'الملاح',
  zoom: 'التكبير',
  animation: 'الرسوم المتحركة',
  crosshair: 'شعاع الاختيار',
  color: 'اللون',
  thickness: 'السمك',
  preferredLength: 'الطول المفضل',
  xType: 'نوع X',
  axisType: 'نوع المحور',
  automatic: 'تلقائي',
  category: 'فئة',
  number: 'عدد',
  time: 'زمن',
  timeFormat: 'تنسيق الوقت',
  autoRotate: 'دوران تلقائي',
  labelRotation: 'الدوران',
  circle: 'دائرة',
  polygon: 'مضلع',
  orientation: 'الاتجاه',
  fixed: 'ثابت',
  parallel: 'متوازي',
  perpendicular: 'عمودي',
  radiusAxisPosition: 'الموضع',
  ticks: 'علامات',
  gridLines: 'خطوط الشبكة',
  width: 'العرض',
  height: 'الارتفاع',
  length: 'الطول',
  padding: 'الحشو',
  spacing: 'التباعد',
  chart: 'الرسم البياني',
  title: 'العنوان',
  titlePlaceholder: 'عنوان الرسم البياني - انقر نقرًا مزدوجًا للتحرير',
  background: 'الخلفية',
  font: 'الخط',
  top: 'أعلى',
  right: 'يمين',
  bottom: 'أسفل',
  left: 'يسار',
  labels: 'التسميات',
  calloutLabels: 'تسميات الاستدعاء',
  sectorLabels: 'تسميات القطاع',
  positionRatio: 'نسبة الموضع',
  size: 'الحجم',
  shape: 'الشكل',
  minSize: 'الحجم الأدنى',
  maxSize: 'الحجم الأقصى',
  legend: 'الأسطورة',
  position: 'الموضع',
  markerSize: 'حجم العلامة',
  markerStroke: 'تحديد العلامة',
  markerPadding: 'حشو العلامة',
  itemSpacing: 'تباعد العنصر',
  itemPaddingX: 'حشو العنصر X',
  itemPaddingY: 'حشو العنصر Y',
  layoutHorizontalSpacing: 'تباعد أفقي',
  layoutVerticalSpacing: 'تباعد رأسي',
  strokeWidth: 'عرض الخط',
  offset: 'الإزاحة',
  offsets: 'الإزاحات',
  tooltips: 'تلميحات الأدوات',
  callout: 'استدعاء',
  markers: 'علامات',
  shadow: 'الظل',
  blur: 'الضبابية',
  xOffset: 'إزاحة X',
  yOffset: 'إزاحة Y',
  lineWidth: 'عرض الخط',
  lineDash: 'نمط الخط',
  lineDashOffset: 'إزاحة الشق',
  scrollingZoom: 'التمرير',
  scrollingStep: 'خطوة التمرير',
  selectingZoom: 'التحديد',
  durationMillis: 'المدة (مللي ثانية)',
  crosshairLabel: 'التسمية',
  crosshairSnap: 'معايرة للعقدة',
  normal: 'عادي',
  bold: 'عريض',
  italic: 'مائل',
  boldItalic: 'عريض مائل',
  predefined: 'محدد مسبقا',
  fillOpacity: 'تعتيم الملء',
  strokeColor: 'لون الخط',
  strokeOpacity: 'تعتيم الخط',
  miniChart: 'رسم بياني مصغر',
  histogramBinCount: 'عدد الحاويات',
  connectorLine: 'خط الربط',
  seriesItems: 'عناصر السلسلة',
  seriesItemType: 'نوع العنصر',
  seriesItemPositive: 'إيجابي',
  seriesItemNegative: 'سلبي',
  seriesItemLabels: 'تسميات العنصر',
  columnGroup: 'عمود',
  barGroup: 'شريط',
  pieGroup: 'قطاع',
  lineGroup: 'خط',
  scatterGroup: 'تشتت',
  bubbleGroup: 'فقاعة',
  areaGroup: 'منطقة',
  xyGroup: 'X Y',
  seriesData: 'البيانات',
  dataRange: 'النطاق',
  sizeRange: 'نطاق الحجم',
  baseRange: 'النطاق الأساسي',
  start: 'بداية',
  end: 'نهاية',
  endWidth: 'عرض النهاية',
  center: 'مركز',
  innerRadius: 'النصف الداخلي',
  outerRadius: 'النصف الخارجي',
  angleRange: 'نطاق الزاوية',
  startAngle: 'زاوية البداية',
  sweepAngle: 'زاوية الانتشار',
  orientationAngle: 'زاوية التوجيه',
  hemisphere: 'نصف الكرة',
  radius: 'نصف القطر',
  equator: 'خط الاستواء',
  centralLongitude: 'خط الطول المركزي',
  centralLatitude: 'خط العرض المركزي',
  mapData: 'الخريطة',
  mapProjection: 'العرض الخرائطي',
  mapLayers: 'طبقات الخريطة',
  mapZoom: 'التكبير',
  mapCenter: 'المركز',
  mapExtent: 'المدى',
  mapPan: 'انتقال',
  mapScale: 'المقياس',
  mapScaleFactor: 'عامل التكبير',
  mapProjectionName: 'اسم العرض الخرائطي',
  mapProjectionType: 'نوع العرض الخرائطي',
  northPole: 'قطب الشمال',
  southPole: 'قطب الجنوب',
  azimuthal: 'قطبي',
  cylindrical: 'أسطواني',
  planar: 'مسطح',
  conic: 'مخروطي',
  oval: 'بيضوي',
  orthographic: 'منظوري',
  mercator: 'ميركاتور',
  transverse: 'مستعرض',
  gnomonic: 'نومونيك',
  stereographic: 'الاستيريوجرافي',
  sizeTypes: 'أنواع الحجم',
  shapeTypes: 'أنواع الشكل',
  density: 'الكثافة',
  snapshot: 'لقطة',

  // السلاسل
  invalidDate: 'تاريخ غير صالح',
  invalidRadius: 'نصف القطر غير صالح',
  invalidTime: 'زمن غير صالح',
  invalidLongitude: 'خط الطول غير صالح',
  invalidLatitude: 'خط العرض غير صالح',
  invalidProjection: 'العرض الخرائطي غير صالح',
  invalidTransformation: 'التحويل غير صالح',
  windowUndefined: 'لا يوجد نافذة غير معرفة',
  windowSize: 'حجم النافذة',
  extentUndefined: 'المدى غير معرف',
  scaleUndefined: 'المقياس غير معرف',
  invalidMinMax: 'حد الحدود غير صالح',
  invalidMaxGreaterThanMin: 'الحد الأقصى يجب أن يكون أكبر من الحد الأدنى',
  incompatibleProjection: 'العرض الخرائطي غير متوافق مع المسارين',
  invalidTimeRange: 'نطاق زمن غير صالح',
  invalidExtentRange: 'نطاق مدى غير صالح',
  invalidDataExtent: 'المدى البيانات غير صالح',
  dataExtent: 'المدى البيانات',
  invalidMapLayers: 'طبقات الخريطة غير صالحة',
  noMapLayers: 'لا توجد طبقات خريطة',
  invalidProjectionName: 'اسم العرض الخرائطي غير صالح',
  invalidProjectionType: 'نوع العرض الخرائطي غير صالح',
  invalidScaleFactor: 'عامل التكبير غير صالح',
  invalidFont: 'الخط غير صالح',
  invalidPosition: 'الموضع غير صالح',
  invalidRotation: 'الدوران غير صالح',
  invalidAngle: 'الزاوية غير صالحة',
  invalidAxis: 'المحور غير صالح',
  invalidWidth: 'العرض غير صالح',
  invalidHeight: 'الارتفاع غير صالح',
  invalidLength: 'الطول غير صالح',
  invalidRadiusRange: 'نطاق نصف القطر غير صالح',
  invalidStrokeWidth: 'عرض الخط غير صالح',
  invalidMarkerSize: 'حجم العلامة غير صالح',
  invalidMarkerStroke: 'تحديد العلامة غير صالح',
  invalidMarkerPadding: 'حشو العلامة غير صالح',
  invalidItemSpacing: 'تباعد العنصر غير صالح',
  invalidItemPaddingX: 'حشو العنصر X غير صالح',
  invalidItemPaddingY: 'حشو العنصر Y غير صالح',
  invalidLayoutHorizontalSpacing: 'تباعد أفقي غير صالح',
  invalidLayoutVerticalSpacing: 'تباعد رأسي غير صالح',
  invalidFillOpacity: 'تعتيم الملء غير صالح',
  invalidStrokeColor: 'لون الخط غير صالح',
  invalidStrokeOpacity: 'تعتيم الخط غير صالح',
  invalidFillType: 'نوع الملء غير صالح',
  invalidLineDash: 'نمط الخط غير صالح',
  invalidLineDashOffset: 'إزاحة الشق غير صالحة',
  invalidMarkerType: 'نوع العلامة غير صالح',
  invalidMarkerShape: 'شكل العلامة غير صالح',
  invalidXType: 'نوع X غير صالح',
  invalidAxisType: 'نوع المحور غير صالح',
  invalidAutomatic: 'النوع التلقائي غير صالح',
  invalidOrientation: 'الاتجاه غير صالح',
  invalidCircle: 'الدائرة غير صالحة',
  invalidPolygon: 'المضلع غير صالح',
  invalidNormal: 'العادي غير صالح',
  invalidBold: 'العريض غير صالح',
  invalidItalic: 'المائل غير صالح',
  invalidBoldItalic: 'العريض المائل غير صالح',
  invalidDegree: 'الدرجة غير صالحة',
  invalidMiniChart: 'رسم بياني مصغر غير صالح',
  invalidHistogramBinCount: 'عدد الحاويات غير صالح',
  invalidConnectorLine: 'خط الربط غير صالح',
  invalidSeriesItemType: 'نوع العنصر غير صالح',
  invalidColumnGroup: 'عمود غير صالح',
  invalidBarGroup: 'شريط غير صالح',
  invalidPieGroup: 'قطاع غير صالح',
  invalidLineGroup: 'خط غير صالح',
  invalidScatterGroup: 'تشتت غير صالح',
  invalidBubbleGroup: 'فقاعة غير صالحة',
  invalidAreaGroup: 'منطقة غير صالحة',
  invalidXyGroup: 'X Y غير صالح',
  invalidSeriesData: 'بيانات السلسلة غير صالحة',
  invalidDataRange: 'نطاق البيانات غير صالح',
  invalidSizeRange: 'نطاق الحجم غير صالح',
  invalidBaseRange: 'نطاق القاعدة غير صالح',
  invalidStart: 'البداية غير صالحة',
  invalidEnd: 'النهاية غير صالحة',
  invalidEndWidth: 'عرض النهاية غير صالح',
  invalidCenter: 'المركز غير صالح',
  invalidInnerRadius: 'النصف الداخلي غير صالح',
  invalidOuterRadius: 'النصف الخارجي غير صالح',
  invalidAngleRange: 'نطاق الزاوية غير صالح',
  invalidStartAngle: 'زاوية البداية غير صالحة',
  invalidSweepAngle: 'زاوية الانتشار غير صالحة',
  invalidOrientationAngle: 'زاوية التوجيه غير صالحة',
  invalidHemisphere: 'نصف الكرة غير صالح',
  invalidEquator: 'خط الاستواء غير صالح',
  invalidCentralLongitude: 'خط الطول المركزي غير صالح',
  invalidCentralLatitude: 'خط العرض المركزي غير صالح',
  invalidMapData: 'بيانات الخريطة غير صالحة',
  invalidMapZoom: 'التكبير غير صالح',
  invalidMapCenter: 'المركز غير صالح',
  invalidMapExtent: 'المدى غير صالح',
  invalidMapPan: 'الانتقال غير صالح',
  invalidMapScale: 'المقياس غير صالح',
  invalidMapScaleFactor: 'عامل التكبير غير صالح',
  invalidMapProjectionName: 'اسم العرض الخرائطي غير صالح',
  invalidMapProjectionType: 'نوع العرض الخرائطي غير صالح',

  // القوائم
  listItem: 'عنصر القائمة',
  listRange: 'نطاق القائمة',
  listMode: 'وضع القائمة',
  listHeader: 'عنوان القائمة',
  listDescription: 'وصف القائمة',
  listRangeStart: 'بداية النطاق',
  listRangeEnd: 'نهاية النطاق',
  listVisibleItems: 'العناصر المرئية',
  listVertical: 'عمودي',
  listHorizontal: 'أفقي',

  // أخرى
  notRendered: 'غير مُعرض',
  loading: 'جار التحميل...',
  clear: 'مسح',
  active: 'نشط',
  field: 'حقل',
  null: 'لا شيء',
  separator: 'فاصل',
  image: 'صورة',
  imageSource: 'مصدر الصورة',
  error: 'خطأ',
  selected: 'محدد',
  key: 'مفتاح',
  value: 'قيمة',
  setting: 'إعداد',
  delete: 'حذف',
  set: 'تعيين',
  insert: 'إدراج',
  update: 'تحديث',
  scroll: 'تمرير',
  axisScroll: 'تمرير المحور',
  language: 'لغة',
  caption: 'الشرح التوضيحي',
  captionPlaceholder: 'توضيحي للصورة - انقر نقرًا مزدوجًا للتحرير',

  // رسائل الأخطاء الشائعة
  failedToCreateComponent: 'فشل إنشاء مكون {0}',
  failedToRenderComponent: 'فشل عرض مكون {0}',
  failedToRenderInvalidType: 'فشل عرض نوع غير صالح ({0})',
  failedToRenderInvalidDimension: 'فشل عرض بعد غير صالح ({0})',
  failedToRenderInvalidObject: 'فشل عرض كائن غير صالح',
  failedToRenderEmptyObject: 'فشل عرض كائن فارغ',
  failedToRenderNullObject: 'فشل عرض كائن فارغ',
  failedToRenderData: 'فشل عرض البيانات',
  failedToRender: 'فشل العرض',
  noDataToRender: 'لا توجد بيانات لعرضها',
  fieldNotFound: 'لم يتم العثور على الحقل {0}',
  invalidParameter: 'المعلمة غير صالحة',
  duplicateParameter: 'المعلمة المكررة: {0}',
  missingParameter: 'معلمة مفقودة: {0}',
  invalidModel: 'النموذج غير صالح',
  invalidType: 'النوع غير صالح',
  invalidValue: 'القيمة غير صالحة',
  invalidAttribute: 'السمة غير صالحة',
  invalidFunction: 'الوظيفة غير صالحة',
  invalidFormat: 'التنسيق غير صالح',
  invalidCategory: 'الفئة غير صالحة',
  invalidFieldType: 'نوع الحقل غير صالح',
  invalidChartType: 'نوع الرسم البياني غير صالح',
  invalidElementType: 'نوع العنصر غير صالح',
  invalidProperty: 'الخاصية غير صالحة',
  invalidScale: 'المقياس غير صالح',
  invalidData: 'البيانات غير صالحة',
  invalidDataSource: 'مصدر البيانات غير صالح',
  invalidSeries: 'سلسلة غير صالحة',

  // ARIA
  ariaAdvancedFilterBuilderItem: '${variable}. المستوى ${variable}. اضغط على ENTER للتحرير.',
  ariaAdvancedFilterBuilderItemValidation: '${variable}. المستوى ${variable}. ${variable} اضغط على ENTER للتحرير.',
  ariaAdvancedFilterBuilderList: 'قائمة بناء عامل التصفية المتقدم',
  ariaAdvancedFilterBuilderFilterItem: 'شرط التصفية',
  ariaAdvancedFilterBuilderGroupItem: 'مجموعة التصفية',
  ariaAdvancedFilterBuilderColumn: 'العمود',
  ariaAdvancedFilterBuilderOption: 'الخيار',
  ariaAdvancedFilterBuilderValueP: 'القيمة',
  ariaAdvancedFilterBuilderJoinOperator: 'عامل الانضمام',
  ariaAdvancedFilterInput: 'مدخل التصفية المتقدمة',
  ariaChecked: 'تم التحديد',
  ariaColumn: 'العمود',
  ariaColumnGroup: 'مجموعة الأعمدة',
  ariaColumnFiltered: 'تم تصفية العمود',
  ariaColumnSelectAll: 'تبديل تحديد جميع الأعمدة',
  ariaDateFilterInput: 'مدخل تصفية التاريخ',
  ariaDefaultListName: 'قائمة',
  ariaFilterColumnsInput: 'مدخل تصفية الأعمدة',
  ariaFilterFromValue: 'تصفية من القيمة',
  ariaFilterInput: 'مدخل التصفية',
  ariaFilterList: 'قائمة التصفية',
  ariaFilterToValue: 'تصفية إلى القيمة',
  ariaFilterValue: 'قيمة التصفية',
  ariaFilterMenuOpen: 'فتح قائمة التصفية',
  ariaFilteringOperator: 'عامل التصفية',
  ariaHidden: 'مخفي',
  ariaIndeterminate: 'غير مُحدَّد',
  ariaInputEditor: 'محرر المدخلات',
  ariaMenuColumn: 'اضغط على ALT DOWN لفتح قائمة الأعمدة',
  ariaFilterColumn: 'اضغط على CTRL ENTER لفتح التصفية',
  ariaRowDeselect: 'اضغط على SPACE لإلغاء تحديد هذا الصف',
  ariaRowSelectAll: 'اضغط على الفراغ لتبديل تحديد جميع الصفوف',
  ariaRowToggleSelection: 'اضغط على SPACE لتبديل تحديد الصف',
  ariaRowSelect: 'اضغط على SPACE لتحديد هذا الصف',
  ariaRowSelectionDisabled: 'تم تعطيل تحديد الصف لهذا الصف',
  ariaSearch: 'بحث',
  ariaSortableColumn: 'اضغط على ENTER للفرز',
  ariaToggleVisibility: 'اضغط على SPACE لتبديل الرؤية',
  ariaToggleCellValue: 'اضغط على SPACE لتبديل قيمة الخلية',
  ariaUnchecked: 'غير محدد',
  ariaVisible: 'مرئي',
  ariaSearchFilterValues: 'البحث في قيم التصفية',
  ariaPageSizeSelectorLabel: 'حجم الصفحة',
  ariaChartMenuClose: 'إغلاق قائمة تحرير الرسم البياني',
  ariaSkeletonCellLoadingFailed: 'فشل تحميل الصف',
  ariaSkeletonCellLoading: 'تحميل بيانات الصف',

  // تسميات ARIA لمناطق الإسقاط
  ariaRowGroupDropZonePanelLabel: 'مجموعات الصفوف',
  ariaValuesDropZonePanelLabel: 'القيم',
  ariaPivotDropZonePanelLabel: 'عناوين الأعمدة',
  ariaDropZoneColumnComponentDescription: 'اضغط على DELETE لإزالة',
  ariaDropZoneColumnValueItemDescription: 'اضغط على ENTER لتغيير نوع التجميع',
  ariaDropZoneColumnGroupItemDescription: 'اضغط على ENTER للفرز',
  // تستخدم لمنطقة الإسقاط التجميعية، الشكل: {تجميع}{ariaDropZoneColumnComponentAggFuncSeparator}{اسم العمود}
  ariaDropZoneColumnComponentAggFuncSeparator: 'من ',
  ariaDropZoneColumnComponentSortAscending: 'تصاعدي',
  ariaDropZoneColumnComponentSortDescending: 'تنازلي',

  // تسميات ARIA للحواري
  ariaLabelColumnMenu: 'قائمة الأعمدة',
  ariaLabelColumnFilter: 'تصفية العمود',
  ariaLabelCellEditor: 'محرر الخلية',
  ariaLabelDialog: 'حوار',
  ariaLabelSelectField: 'تحديد الحقل',
  ariaLabelRichSelectField: 'تحديد الحقل الغني',
  ariaLabelTooltip: 'تلميح',
  ariaLabelContextMenu: 'قائمة السياق',
  ariaLabelSubMenu: 'قائمة فرعية',
  ariaLabelAggregationFunction: 'وظيفة التجميع',
  ariaLabelAdvancedFilterAutocomplete: 'إكمال تصفية متقدمة',
  ariaLabelAdvancedFilterBuilderAddField: 'إضافة حقل إلى بناء عامل التصفية المتقدم',
  ariaLabelAdvancedFilterBuilderColumnSelectField: 'تحديد حقل العمود في بناء عامل التصفية المتقدم',
  ariaLabelAdvancedFilterBuilderOptionSelectField: 'تحديد حقل الخيار في بناء عامل التصفية المتقدم',
  ariaLabelAdvancedFilterBuilderJoinSelectField: 'تحديد حقل عامل الانضمام في بناء عامل التصفية المتقدم',

  // تسميات ARIA للشريط الجانبي
  ariaColumnPanelList: 'قائمة الأعمدة',
  ariaFilterPanelList: 'قائمة التصفية',

  // تنسيق الأرقام (شريط الحالة، لوحة الترقيم)
  thousandSeparator: ',',
  decimalSeparator: '.',

  // أنواع البيانات
  true: 'صحيح',
  false: 'غير صحيح',
  invalidNumber: 'رقم غير صالح',
  january: 'يناير',
  february: 'فبراير',
  march: 'مارس',
  april: 'أبريل',
  may: 'مايو',
  june: 'يونيو',
  july: 'يوليو',
  august: 'أغسطس',
  september: 'سبتمبر',
  october: 'أكتوبر',
  november: 'نوفمبر',
  december: 'ديسمبر',
};

